### ISSUE TITLE
Extracting Images

### ISSUE THREAD

**Issue by soner4** [unl-nimbus-lab/bag2matlab#2]
Hi,

I am trying to extract Images and it is causing  matlab to crash(Assertion `Fatal Java Exception.' ). I have tried both compressed and and normal images result is  same. The  problem is not  memory   as I have  32gb  ram and only 10gb is  utilized.  My system is  ubuntu 14.04, Matlab 15a, Indigo. Other  ros msg types are  working  fine. Any  help is appreciated.

Bests,
Xep

**Comment by danthony06** [comment]
I have not been able to reproduce this. I do not have many bags with camera images to test against though. Could you try a couple of things to help me fix this or identify the problem?
1. Have you tried increasing the Java Heap Size in Matlab? This setting is in Matlab Preferences -> General -> Java Heap Memory. I have mine set to 4,011 MB of memory.
2. Can you share a bag file that causes this to happen on your computer? I can use it to reproduce it on my computer.

**Comment by danthony06** [comment]
Commit 61ba6c5 adds the option to specify a minimum and maximum message index so you can extract a smaller chunk of the the bag. This should help if it is a memory exhaustion problem.

**Comment by soner4** [comment]
Hi,

Thanks for the quick reply.  There are  quite a few  number of bags on the  internet. I am posting  a few  for your convenience:
http://rpg.ifi.uzh.ch/datasets/airground_rig_s3_2013-03-18_21-38-48.bag
https://docs.google.com/uc?id=0B46akLGdg-uadXhLeURiMTBQU28&export=download
http://www6.in.tum.de/~kloses/rvc/kitti_bags/ (They are  a bit  large)
http://www.mrpt.org/robotics_datasets  (They are  a bit  large)
http://wiki.ros.org/stereo_image_proc/Tutorials/ChoosingGoodStereoParameters?action=AttachFile&do=view&target=rotating_detergent.bag  (This one is a stereo,images are  not  indexed, thought might be good for testing)   'rosbag reindex rotating_detergent.bag '  in order to index.

Please let me know  if  you need  more bags for test.  I have updated my profile  so that my  email is public. It might be faster  to contact that way.

About matlab my  Java Heap  Memory is also 4012MB. If you can not   reproduce  with these  I will try to get  Matlab 16a and see if it is working. 

I will  try the new comit  and see if it  solves the issue.

**Comment by danthony06** [comment]
Commit 9522dbd fixing extracting images from the bag files, and converting Python strings to Matlab character arrays for all data types. Commit eebe312 is an example of how to convert the data in a bag file to a format Matlab can understand.
